# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jardin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='plante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('date_naissance', models.DateField()),
                ('date_deces', models.DateField()),
                ('id_jardin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardinage.jardin')),
            ],
        ),
        migrations.CreateModel(
            name='variete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='plante',
            name='id_variete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardinage.variete'),
        ),
    ]
